name:Build APK
on:[push,workflow_dispacth]
jobs:
build:
runs-on:ubutu-latest
steps:
-uses:actions/checkout@v4
-uses:actions/setup-java@v4
with:
java-version:'17'
distribution 'Temuçin'in
-uses:
android-actions/setup-android@v3
-run:Cradle asembleDebug
--no-daemon
-uses:actions/upload-artifact@v4
with:
name:jarvis-debug-apk
path:APK/build/outputs/apk/de bugün/app-debug.apk
